### ISSUE TITLE
Create a guide outline as strawman for feedback

### ISSUE THREAD

**Issue by mrchrisadams** [productscience/planet-friendly-web#4]
Rather than waiting until the whole guide is written before getting feedback, it's worth sharing an outline of the key areas, to get early, and frequent feedback.

- [x] Create outline where people can vote and add comments

Here's the link:

http://trello.com/b/I3co3nYM/planet-friendly-web-guide-board

**Comment by jacklenox** [comment]
I'd like to help with this. Is the idea to kind of build a table of contents that would represent the book upon completion? And obviously mould/adapt this ToC as we go?

**Comment by mrchrisadams** [comment]
Oops!

Sorry for the late reply here @jacklenox  - I saw your comments on the guide outline on the [guide outline trello board][1], but I really should add some here too.

Yes, that's pretty much the plan.

[1]: httpss://trello.com/b/I3co3nYM/planet-friendly-web-guide-board
